# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class CalculatorStub(object):
    """Простой сервис калькулятора
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Add = channel.unary_unary(
                '/calculator.Calculator/Add',
                request_serializer=service__pb2.AddRequest.SerializeToString,
                response_deserializer=service__pb2.AddResponse.FromString,
                )
        self.Multiply = channel.unary_unary(
                '/calculator.Calculator/Multiply',
                request_serializer=service__pb2.MultiplyRequest.SerializeToString,
                response_deserializer=service__pb2.MultiplyResponse.FromString,
                )
        self.Greet = channel.unary_unary(
                '/calculator.Calculator/Greet',
                request_serializer=service__pb2.GreetRequest.SerializeToString,
                response_deserializer=service__pb2.GreetResponse.FromString,
                )


class CalculatorServicer(object):
    """Простой сервис калькулятора
    """

    def Add(self, request, context):
        """Сложение двух чисел
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Multiply(self, request, context):
        """Умножение двух чисел
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Greet(self, request, context):
        """Приветствие по имени
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=service__pb2.AddRequest.FromString,
                    response_serializer=service__pb2.AddResponse.SerializeToString,
            ),
            'Multiply': grpc.unary_unary_rpc_method_handler(
                    servicer.Multiply,
                    request_deserializer=service__pb2.MultiplyRequest.FromString,
                    response_serializer=service__pb2.MultiplyResponse.SerializeToString,
            ),
            'Greet': grpc.unary_unary_rpc_method_handler(
                    servicer.Greet,
                    request_deserializer=service__pb2.GreetRequest.FromString,
                    response_serializer=service__pb2.GreetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculator.Calculator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Calculator(object):
    """Простой сервис калькулятора
    """

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calculator.Calculator/Add',
            service__pb2.AddRequest.SerializeToString,
            service__pb2.AddResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Multiply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calculator.Calculator/Multiply',
            service__pb2.MultiplyRequest.SerializeToString,
            service__pb2.MultiplyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Greet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calculator.Calculator/Greet',
            service__pb2.GreetRequest.SerializeToString,
            service__pb2.GreetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
