# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\ncalculator\".\n\nAddRequest\x12\x0f\n\x07number1\x18\x01 \x01(\x01\x12\x0f\n\x07number2\x18\x02 \x01(\x01\"\x1d\n\x0b\x41\x64\x64Response\x12\x0e\n\x06result\x18\x01 \x01(\x01\"3\n\x0fMultiplyRequest\x12\x0f\n\x07number1\x18\x01 \x01(\x01\x12\x0f\n\x07number2\x18\x02 \x01(\x01\"\"\n\x10MultiplyResponse\x12\x0e\n\x06result\x18\x01 \x01(\x01\"\x1c\n\x0cGreetRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\rGreetResponse\x12\x10\n\x08greeting\x18\x01 \x01(\t2\xcf\x01\n\nCalculator\x12\x38\n\x03\x41\x64\x64\x12\x16.calculator.AddRequest\x1a\x17.calculator.AddResponse\"\x00\x12G\n\x08Multiply\x12\x1b.calculator.MultiplyRequest\x1a\x1c.calculator.MultiplyResponse\"\x00\x12>\n\x05Greet\x12\x18.calculator.GreetRequest\x1a\x19.calculator.GreetResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ADDREQUEST']._serialized_start=29
  _globals['_ADDREQUEST']._serialized_end=75
  _globals['_ADDRESPONSE']._serialized_start=77
  _globals['_ADDRESPONSE']._serialized_end=106
  _globals['_MULTIPLYREQUEST']._serialized_start=108
  _globals['_MULTIPLYREQUEST']._serialized_end=159
  _globals['_MULTIPLYRESPONSE']._serialized_start=161
  _globals['_MULTIPLYRESPONSE']._serialized_end=195
  _globals['_GREETREQUEST']._serialized_start=197
  _globals['_GREETREQUEST']._serialized_end=225
  _globals['_GREETRESPONSE']._serialized_start=227
  _globals['_GREETRESPONSE']._serialized_end=260
  _globals['_CALCULATOR']._serialized_start=263
  _globals['_CALCULATOR']._serialized_end=470
# @@protoc_insertion_point(module_scope)
